services:
  kotlin-app:
    build: .
    container_name: kotlin-docker-hello-world
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    volumes:
      - ./build/libs:/app/build/libs  # ローカルとコンテナのJARファイルディレクトリを同期
      - ./src:/app/src                # ローカルのソースコードをコンテナ内に同期
      - ./build.gradle.kts:/app/build.gradle.kts  # Gradle設定ファイルを同期
      - ./settings.gradle.kts:/app/settings.gradle.kts  # 同じく設定ファイルを同期
